version: "3"

services:

  mongodb:
    image: mongo:3.2

  server:
    build: server/

    command: python ./server.py

    ports:
      - 5000:5000

    depends_on:
      - mongodb

    links:
      - mongodb
